version: "3"
services:
  go-exercises-worker:
    build: ./go-exercises-worker
    environment:
      ALLOWED_IMPORT_CONFIG: /etc/go-exercises-worker/allowed_imports.json
    command:
      - /usr/local/bin/wait-for-it.sh
      - localhost:5672
      - --
      - /usr/local/bin/go-exercises-worker
    volumes:
      - ./go-exercises-worker/configs:/etc/go-exercises-worker
    network_mode: host

  go-exercises-backend:
    build: ./go-exercises-backend
    environment:
      SERVER_ADDRESS: ":8080"
      SERVER_STATIC_FILE_PATH: /var/www/go-exercises-backend
    ports:
      - 8080:8080
    volumes:
      - ./go-exercises-backend/static:/var/www/go-exercises-backend
    command:
      - /usr/local/bin/wait-for-it.sh
      - localhost:5432
      - --
      - /usr/local/bin/wait-for-it.sh
      - localhost:5672
      - --
      - /usr/local/bin/go-exercises-backend
    network_mode: host

  go-exercises-frontend:
    build: ./go-exercises-frontend
    volumes:
      - ./go-exercises-backend/static:/node/src/go-exercises-frontend/build-external
    command:
      - cp
      - --recursive
      - --no-target-directory
      - /node/src/go-exercises-frontend/build
      - /node/src/go-exercises-frontend/build-external
