version: "3"
services:
  go-exercises-worker:
    build: ./go-exercises-worker
    environment:
      MESSAGE_BROKER_ADDRESS: amqp://rabbitmq:rabbitmq@rabbitmq:5672
      ALLOWED_IMPORT_CONFIG: /etc/go-exercises-worker/allowed_imports.json
    command:
      - /usr/local/bin/wait-for-it.sh
      - rabbitmq:5672
      - --
      - /usr/local/bin/go-exercises-worker
    volumes:
      - ./go-exercises-worker/configs:/etc/go-exercises-worker

  go-exercises-backend:
    build: ./go-exercises-backend
    environment:
      SERVER_ADDRESS: ":8080"
      SERVER_STATIC_FILE_PATH: /var/www/go-exercises-backend
      STORAGE_ADDRESS: postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
      MESSAGE_BROKER_ADDRESS: amqp://rabbitmq:rabbitmq@rabbitmq:5672
    ports:
      - 8080:8080
    volumes:
      - ./go-exercises-backend/static:/var/www/go-exercises-backend
    command:
      - /usr/local/bin/wait-for-it.sh
      - postgres:5432
      - --
      - /usr/local/bin/wait-for-it.sh
      - rabbitmq:5672
      - --
      - /usr/local/bin/go-exercises-backend

  go-exercises-frontend:
    build: ./go-exercises-frontend
    volumes:
      - ./go-exercises-backend/static:/node/src/go-exercises-frontend/build-external
    command:
      - cp
      - --recursive
      - --no-target-directory
      - /node/src/go-exercises-frontend/build
      - /node/src/go-exercises-frontend/build-external

  postgres:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

  adminer:
    image: adminer:4.8.0
    ports:
      - 9090:8080

  rabbitmq:
    image: rabbitmq:3.8.14-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    ports:
      - 5672:5672 # RabbitMQ server
      - 15672:15672 # RabbitMQ management plugin

  go-exercises-worker-asyncapi-generator:
    image: asyncapi/generator:1.9.0
    command:
      - --debug
      - --install
      - --output=/app/async-api
      - --force-write
      - /app/async_api.yaml
      - "@asyncapi/html-template@0.24.8"
    volumes:
      - ./go-exercises-worker/docs/async_api.yaml:/app/async_api.yaml
      - ./go-exercises-worker/docs/async-api:/app/async-api

  go-exercises-worker-asyncapi:
    image: nginx:1.21.1-alpine
    ports:
      - 9091:80
    volumes:
      - ./go-exercises-worker/docs/async-api:/usr/share/nginx/html

  go-exercises-backend-asyncapi-generator:
    image: asyncapi/generator:1.9.0
    command:
      - --debug
      - --install
      - --output=/app/async-api
      - --force-write
      - /app/async_api.yaml
      - "@asyncapi/html-template@0.24.8"
    volumes:
      - ./go-exercises-backend/docs/async_api.yaml:/app/async_api.yaml
      - ./go-exercises-backend/docs/async-api:/app/async-api

  go-exercises-backend-asyncapi:
    image: nginx:1.21.1-alpine
    ports:
      - 9092:80
    volumes:
      - ./go-exercises-backend/docs/async-api:/usr/share/nginx/html

  swagger:
    image: swaggerapi/swagger-ui:v3.24.0
    environment:
      SWAGGER_JSON: /etc/go-exercises-backend/swagger.json
    ports:
      - 9093:8080
    volumes:
      - ./go-exercises-backend/docs/swagger.json:/etc/go-exercises-backend/swagger.json
